import { describe, expect, it } from 'vitest'
import { changeOf, eventsOfMessage, modelOfOutput, modelValueOf } from '../server/sessions.ts'

// Taken from quack-board (tests/unit/claude_transcript.spec.ts, Simon's): a saved session is read from Claude Code's
// transcript, its messages as Claude Code writes them.
describe('Claude transcript', () => {
  it('an answer mixing text and tool calls shows each of them', () => {
    // A tool call has no `content` and a text has no `input`: neither must drop the message.
    const answer = {
      type: 'assistant',
      message: {
        role: 'assistant',
        content: [
          { type: 'text', text: 'Je regarde le fichier.' },
          { type: 'tool_use', id: 'toolu_1', name: 'Read', input: { file_path: 'src/a.ts' }, caller: { type: 'direct' } },
        ],
      },
    }
    const result = {
      type: 'user',
      message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'toolu_1', content: 'export const a = 1' }] },
    }
    expect(eventsOfMessage(answer)).toEqual([
      { kind: 'text', text: 'Je regarde le fichier.' },
      { kind: 'tool', id: 'toolu_1', name: 'Read', detail: 'src/a.ts', change: null },
    ])
    expect(eventsOfMessage(result)).toEqual([{ kind: 'tool_result', id: 'toolu_1', ok: true, text: 'export const a = 1' }])
  })

  it('a message typed by the user is one line', () => {
    expect(eventsOfMessage({ type: 'user', message: { content: 'bonjour' } })).toEqual([{ kind: 'user', text: 'bonjour' }])
  })

  it('a slash command Claude Code ran is shown as typed, its output as a note', () => {
    const user = (content: string) => eventsOfMessage({ type: 'user', message: { content } })
    expect(
      user('<command-name>/plugin</command-name>\n            <command-message>plugin</command-message>\n            <command-args></command-args>')
    ).toEqual([{ kind: 'user', text: '/plugin' }])
    expect(user('<command-name>/model</command-name><command-message>model</command-message><command-args>opus</command-args>')).toEqual([
      { kind: 'user', text: '/model opus' },
    ])
    expect(user('<local-command-stdout>\u001b[1m✓\u001b[22m Removed 1 marketplace</local-command-stdout>')).toEqual([
      { kind: 'info', text: '✓ Removed 1 marketplace' },
    ])
    // Nothing to say, or written for Claude alone.
    expect(user('<local-command-stdout>(no content)</local-command-stdout>')).toEqual([])
    expect(user('<local-command-stdout></local-command-stdout>')).toEqual([])
    expect(user('<local-command-caveat>Caveat: the messages below were generated by the user…</local-command-caveat>')).toEqual([])
    // A skill run as a command, the message first; a background task that ended.
    expect(user('<command-message>design</command-message>\n<command-name>/design</command-name>')).toEqual([{ kind: 'user', text: '/design' }])
    expect(
      user(
        '<task-notification>\n<task-id>bn2</task-id>\n<status>completed</status>\n<summary>Background command "Build" completed (exit code 0)</summary>\n</task-notification>'
      )
    ).toEqual([{ kind: 'info', text: 'Background command "Build" completed (exit code 0)' }])
    // The same in a text block.
    expect(
      eventsOfMessage({ type: 'user', message: { content: [{ type: 'text', text: '<command-name>/reload-plugins</command-name>' }] } })
    ).toEqual([{ kind: 'user', text: '/reload-plugins' }])
  })

  it('reads the model a /model command switched to, and the field’s value behind it', () => {
    expect(modelOfOutput('Set model to `claude-opus-5-5`')).toBe('claude-opus-5-5')
    expect(modelOfOutput('Set model to `Opus 5.5` for this session only')).toBe('Opus 5.5')
    expect(modelOfOutput('Set model to Sonnet 5.5 for this session only')).toBe('Sonnet 5.5')
    expect(modelOfOutput('Kept model as opus')).toBeNull()
    const models = [
      { value: 'claude-opus-5-5', label: 'Opus 5.5', description: '', efforts: [] },
      { value: 'claude-sonnet-5-5', label: 'Sonnet 5.5', description: '', efforts: [] },
    ]
    expect(modelValueOf(models, 'Opus 5.5')).toBe('claude-opus-5-5')
    expect(modelValueOf(models, 'claude-sonnet-5-5')).toBe('claude-sonnet-5-5')
    expect(modelValueOf(models, 'claude-haiku-9')).toBe('claude-haiku-9')
    expect(modelValueOf(models, 'Unknown')).toBeNull()
  })

  it('a tool call that changes a file carries its diff', () => {
    expect(changeOf('Edit', { file_path: 'a.ts', old_string: 'x', new_string: 'y' })).toEqual({ file: 'a.ts', before: 'x', after: 'y' })
    expect(changeOf('Write', { file_path: 'b.ts', content: 'z' })).toEqual({ file: 'b.ts', before: '', after: 'z' })
    expect(
      changeOf('MultiEdit', {
        file_path: 'c.ts',
        edits: [
          { old_string: 'a', new_string: 'b' },
          { old_string: 'c', new_string: 'd' },
        ],
      })
    ).toEqual({ file: 'c.ts', before: 'a\n…\nc', after: 'b\n…\nd' })
    expect(changeOf('Read', { file_path: 'a.ts' })).toBeNull()
  })
})
